name: Build, publish and deploy

on:
  workflow_run:
    workflows: ["Tests"]
    branches: ["master"]
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_PROD }}
  GKE_CLUSTER: sandbox
  GKE_ZONE: us-central1-c
  IMAGE_API: mobility-api
  IMAGE_APP: mobility-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY_PROD }}
          project_id: ${{ secrets.GKE_PROJECT_PROD }}

      - name: Configure Docker with gcloud
        run: |-
          gcloud --quiet auth configure-docker
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY_PROD }}

      - name: Build API Docker image
        run: |-
          docker build \
            --file Dockerfile.api \
            --tag "gcr.io/$PROJECT_ID/$IMAGE_API:$GITHUB_SHA" \
            .

      - name: Publish API Docker image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE_API:$GITHUB_SHA"

      - name: Build web app Docker image
        run: |-
          docker build \
            --file Dockerfile.app \
            --tag "gcr.io/$PROJECT_ID/$IMAGE_APP:$GITHUB_SHA" \
            .

      - name: Publish web app Docker image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE_APP:$GITHUB_SHA"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE_API:TAG=gcr.io/$PROJECT_ID/$IMAGE_API:$GITHUB_SHA
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE_APP:TAG=gcr.io/$PROJECT_ID/$IMAGE_APP:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl get services -o wide
